version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: "mysql"
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
    cap_add:
      - SYS_ADMIN

  app:
    build: .
    restart: on-failure
    container_name: "fastapi"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    tty: true
