version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: 'mysql'
    expose:
      - '$MYSQL_PORT'
    env_file:
      - .env
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
    cap_add:
      - SYS_ADMIN

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=/usr/src/app
    restart: on-failure
    container_name: 'fastapi'
    ports:
      - '$APP_PORT:$APP_PORT'
    env_file:
      - .env
    depends_on:
      - db
    tty: true
