version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: "mysql"
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
    cap_add:
      - SYS_ADMIN

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: "fastapi"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    tty: true
