"""Add pinned column on Memos

Revision ID: 00b013324821
Revises: c4d79a532148
Create Date: 2021-09-16 00:41:44.359272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b013324821'
down_revision = 'c4d79a532148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('pinned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memos', 'pinned')
    # ### end Alembic commands ###
