"""Add Disabled col

Revision ID: 1ae4af70a2f0
Revises: 649689436ad1
Create Date: 2021-06-16 15:44:41.487912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae4af70a2f0'
down_revision = '649689436ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.create_index(
        op.f('ix_users_disabled'), 'users', ['disabled'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_disabled'), table_name='users')
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
