"""Change datetime automatically for user

Revision ID: 22a8fae18f7d
Revises: e4a3d91892ff
Create Date: 2021-06-24 01:32:40.229287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22a8fae18f7d'
down_revision = 'e4a3d91892ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
