"""Change string length

Revision ID: 649689436ad1
Revises: d2ebabefc791
Create Date: 2021-06-18 16:08:28.754531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '649689436ad1'
down_revision = 'd2ebabefc791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('user_id', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
