"""First revision

Revision ID: 75c80cff56bd
Revises: e38020c7579a
Create Date: 2021-05-31 13:42:36.110260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c80cff56bd'
down_revision = 'e38020c7579a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('containts', sa.String(length=2000), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(length=2000), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_datetime'), 'memos', ['datetime'], unique=False)
    op.create_index(op.f('ix_memos_id'), 'memos', ['id'], unique=False)
    op.create_index(op.f('ix_memos_is_removed'), 'memos', ['is_removed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memos_is_removed'), table_name='memos')
    op.drop_index(op.f('ix_memos_id'), table_name='memos')
    op.drop_index(op.f('ix_memos_datetime'), table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
