"""Change relationship

Revision ID: 8ae3aeb6dafe
Revises: de3bdf5a9ff8
Create Date: 2021-06-23 02:18:18.328967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae3aeb6dafe'
down_revision = 'de3bdf5a9ff8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
