"""Fix typo

Revision ID: c3c6a40821a1
Revises: 22a8fae18f7d
Create Date: 2021-09-06 00:29:45.542758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3c6a40821a1'
down_revision = '22a8fae18f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('contents', sa.Text(), nullable=False))
    op.drop_column('memos', 'containts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('containts', mysql.VARCHAR(length=2000), nullable=True))
    op.drop_column('memos', 'contents')
    # ### end Alembic commands ###
