"""Add datetime col

Revision ID: d2ebabefc791
Revises: ae50678c2ad6
Create Date: 2021-06-14 11:37:31.917734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2ebabefc791'
down_revision = 'ae50678c2ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
