"""First revision

Revision ID: e38020c7579a
Revises:
Create Date: 2021-05-31 12:50:49.927431

"""

# revision identifiers, used by Alembic.
revision = 'e38020c7579a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
