"""Change datetime automatically

Revision ID: e4a3d91892ff
Revises: 8ae3aeb6dafe
Create Date: 2021-06-24 01:11:12.679651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4a3d91892ff'
down_revision = '8ae3aeb6dafe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('memos', sa.Column('updated', sa.DateTime(), nullable=True))
    op.drop_index('ix_memos_datetime', table_name='memos')
    op.drop_column('memos', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('datetime', mysql.DATETIME(), nullable=True))
    op.create_index('ix_memos_datetime', 'memos', ['datetime'], unique=False)
    op.drop_column('memos', 'updated')
    op.drop_column('memos', 'created')
    # ### end Alembic commands ###
